# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remoter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rremoter.proto\x12\rremoter.input\"4\n\x06Header\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12\x0c\n\x04t_ms\x18\x03 \x01(\x04\"a\n\x04\x45\x64ge\x12\"\n\x03hdr\x18\x01 \x01(\x0b\x32\x15.remoter.input.Header\x12\x11\n\thid_usage\x18\x02 \x01(\r\x12\x0f\n\x07is_down\x18\x03 \x01(\x08\x12\x11\n\tmodifiers\x18\x04 \x01(\r\"Y\n\x08Snapshot\x12\"\n\x03hdr\x18\x01 \x01(\x0b\x32\x15.remoter.input.Header\x12\x11\n\tmodifiers\x18\x02 \x01(\r\x12\x16\n\x0epressed_bitmap\x18\x03 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remoter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEADER._serialized_start=32
  _HEADER._serialized_end=84
  _EDGE._serialized_start=86
  _EDGE._serialized_end=183
  _SNAPSHOT._serialized_start=185
  _SNAPSHOT._serialized_end=274
# @@protoc_insertion_point(module_scope)
