// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remoter.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_remoter_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_remoter_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_remoter_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_remoter_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_remoter_2eproto;
namespace remoter {
namespace input {
class Edge;
struct EdgeDefaultTypeInternal;
extern EdgeDefaultTypeInternal _Edge_default_instance_;
class Header;
struct HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class Snapshot;
struct SnapshotDefaultTypeInternal;
extern SnapshotDefaultTypeInternal _Snapshot_default_instance_;
}  // namespace input
}  // namespace remoter
PROTOBUF_NAMESPACE_OPEN
template<> ::remoter::input::Edge* Arena::CreateMaybeMessage<::remoter::input::Edge>(Arena*);
template<> ::remoter::input::Header* Arena::CreateMaybeMessage<::remoter::input::Header>(Arena*);
template<> ::remoter::input::Snapshot* Arena::CreateMaybeMessage<::remoter::input::Snapshot>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace remoter {
namespace input {

// ===================================================================

class Header final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:remoter.input.Header) */ {
 public:
  inline Header() : Header(nullptr) {}
  ~Header() override;
  explicit PROTOBUF_CONSTEXPR Header(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Header(const Header& from);
  Header(Header&& from) noexcept
    : Header() {
    *this = ::std::move(from);
  }

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }
  inline Header& operator=(Header&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Header& default_instance() {
    return *internal_default_instance();
  }
  static inline const Header* internal_default_instance() {
    return reinterpret_cast<const Header*>(
               &_Header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Header& a, Header& b) {
    a.Swap(&b);
  }
  inline void Swap(Header* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Header* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Header* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Header>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Header& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Header& from) {
    Header::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Header* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "remoter.input.Header";
  }
  protected:
  explicit Header(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVersionFieldNumber = 1,
    kSeqFieldNumber = 2,
    kTMsFieldNumber = 3,
  };
  // uint32 version = 1;
  void clear_version();
  uint32_t version() const;
  void set_version(uint32_t value);
  private:
  uint32_t _internal_version() const;
  void _internal_set_version(uint32_t value);
  public:

  // uint32 seq = 2;
  void clear_seq();
  uint32_t seq() const;
  void set_seq(uint32_t value);
  private:
  uint32_t _internal_seq() const;
  void _internal_set_seq(uint32_t value);
  public:

  // uint64 t_ms = 3;
  void clear_t_ms();
  uint64_t t_ms() const;
  void set_t_ms(uint64_t value);
  private:
  uint64_t _internal_t_ms() const;
  void _internal_set_t_ms(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:remoter.input.Header)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t version_;
    uint32_t seq_;
    uint64_t t_ms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_remoter_2eproto;
};
// -------------------------------------------------------------------

class Edge final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:remoter.input.Edge) */ {
 public:
  inline Edge() : Edge(nullptr) {}
  ~Edge() override;
  explicit PROTOBUF_CONSTEXPR Edge(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Edge(const Edge& from);
  Edge(Edge&& from) noexcept
    : Edge() {
    *this = ::std::move(from);
  }

  inline Edge& operator=(const Edge& from) {
    CopyFrom(from);
    return *this;
  }
  inline Edge& operator=(Edge&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Edge& default_instance() {
    return *internal_default_instance();
  }
  static inline const Edge* internal_default_instance() {
    return reinterpret_cast<const Edge*>(
               &_Edge_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Edge& a, Edge& b) {
    a.Swap(&b);
  }
  inline void Swap(Edge* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Edge* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Edge* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Edge>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Edge& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Edge& from) {
    Edge::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Edge* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "remoter.input.Edge";
  }
  protected:
  explicit Edge(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHdrFieldNumber = 1,
    kHidUsageFieldNumber = 2,
    kIsDownFieldNumber = 3,
    kModifiersFieldNumber = 4,
  };
  // .remoter.input.Header hdr = 1;
  bool has_hdr() const;
  private:
  bool _internal_has_hdr() const;
  public:
  void clear_hdr();
  const ::remoter::input::Header& hdr() const;
  PROTOBUF_NODISCARD ::remoter::input::Header* release_hdr();
  ::remoter::input::Header* mutable_hdr();
  void set_allocated_hdr(::remoter::input::Header* hdr);
  private:
  const ::remoter::input::Header& _internal_hdr() const;
  ::remoter::input::Header* _internal_mutable_hdr();
  public:
  void unsafe_arena_set_allocated_hdr(
      ::remoter::input::Header* hdr);
  ::remoter::input::Header* unsafe_arena_release_hdr();

  // uint32 hid_usage = 2;
  void clear_hid_usage();
  uint32_t hid_usage() const;
  void set_hid_usage(uint32_t value);
  private:
  uint32_t _internal_hid_usage() const;
  void _internal_set_hid_usage(uint32_t value);
  public:

  // bool is_down = 3;
  void clear_is_down();
  bool is_down() const;
  void set_is_down(bool value);
  private:
  bool _internal_is_down() const;
  void _internal_set_is_down(bool value);
  public:

  // uint32 modifiers = 4;
  void clear_modifiers();
  uint32_t modifiers() const;
  void set_modifiers(uint32_t value);
  private:
  uint32_t _internal_modifiers() const;
  void _internal_set_modifiers(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:remoter.input.Edge)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::remoter::input::Header* hdr_;
    uint32_t hid_usage_;
    bool is_down_;
    uint32_t modifiers_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_remoter_2eproto;
};
// -------------------------------------------------------------------

class Snapshot final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:remoter.input.Snapshot) */ {
 public:
  inline Snapshot() : Snapshot(nullptr) {}
  ~Snapshot() override;
  explicit PROTOBUF_CONSTEXPR Snapshot(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Snapshot(const Snapshot& from);
  Snapshot(Snapshot&& from) noexcept
    : Snapshot() {
    *this = ::std::move(from);
  }

  inline Snapshot& operator=(const Snapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline Snapshot& operator=(Snapshot&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Snapshot& default_instance() {
    return *internal_default_instance();
  }
  static inline const Snapshot* internal_default_instance() {
    return reinterpret_cast<const Snapshot*>(
               &_Snapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Snapshot& a, Snapshot& b) {
    a.Swap(&b);
  }
  inline void Swap(Snapshot* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Snapshot* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Snapshot* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Snapshot>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Snapshot& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Snapshot& from) {
    Snapshot::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Snapshot* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "remoter.input.Snapshot";
  }
  protected:
  explicit Snapshot(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPressedBitmapFieldNumber = 3,
    kHdrFieldNumber = 1,
    kModifiersFieldNumber = 2,
  };
  // bytes pressed_bitmap = 3;
  void clear_pressed_bitmap();
  const std::string& pressed_bitmap() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pressed_bitmap(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pressed_bitmap();
  PROTOBUF_NODISCARD std::string* release_pressed_bitmap();
  void set_allocated_pressed_bitmap(std::string* pressed_bitmap);
  private:
  const std::string& _internal_pressed_bitmap() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pressed_bitmap(const std::string& value);
  std::string* _internal_mutable_pressed_bitmap();
  public:

  // .remoter.input.Header hdr = 1;
  bool has_hdr() const;
  private:
  bool _internal_has_hdr() const;
  public:
  void clear_hdr();
  const ::remoter::input::Header& hdr() const;
  PROTOBUF_NODISCARD ::remoter::input::Header* release_hdr();
  ::remoter::input::Header* mutable_hdr();
  void set_allocated_hdr(::remoter::input::Header* hdr);
  private:
  const ::remoter::input::Header& _internal_hdr() const;
  ::remoter::input::Header* _internal_mutable_hdr();
  public:
  void unsafe_arena_set_allocated_hdr(
      ::remoter::input::Header* hdr);
  ::remoter::input::Header* unsafe_arena_release_hdr();

  // uint32 modifiers = 2;
  void clear_modifiers();
  uint32_t modifiers() const;
  void set_modifiers(uint32_t value);
  private:
  uint32_t _internal_modifiers() const;
  void _internal_set_modifiers(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:remoter.input.Snapshot)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pressed_bitmap_;
    ::remoter::input::Header* hdr_;
    uint32_t modifiers_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_remoter_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Header

// uint32 version = 1;
inline void Header::clear_version() {
  _impl_.version_ = 0u;
}
inline uint32_t Header::_internal_version() const {
  return _impl_.version_;
}
inline uint32_t Header::version() const {
  // @@protoc_insertion_point(field_get:remoter.input.Header.version)
  return _internal_version();
}
inline void Header::_internal_set_version(uint32_t value) {
  
  _impl_.version_ = value;
}
inline void Header::set_version(uint32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:remoter.input.Header.version)
}

// uint32 seq = 2;
inline void Header::clear_seq() {
  _impl_.seq_ = 0u;
}
inline uint32_t Header::_internal_seq() const {
  return _impl_.seq_;
}
inline uint32_t Header::seq() const {
  // @@protoc_insertion_point(field_get:remoter.input.Header.seq)
  return _internal_seq();
}
inline void Header::_internal_set_seq(uint32_t value) {
  
  _impl_.seq_ = value;
}
inline void Header::set_seq(uint32_t value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:remoter.input.Header.seq)
}

// uint64 t_ms = 3;
inline void Header::clear_t_ms() {
  _impl_.t_ms_ = uint64_t{0u};
}
inline uint64_t Header::_internal_t_ms() const {
  return _impl_.t_ms_;
}
inline uint64_t Header::t_ms() const {
  // @@protoc_insertion_point(field_get:remoter.input.Header.t_ms)
  return _internal_t_ms();
}
inline void Header::_internal_set_t_ms(uint64_t value) {
  
  _impl_.t_ms_ = value;
}
inline void Header::set_t_ms(uint64_t value) {
  _internal_set_t_ms(value);
  // @@protoc_insertion_point(field_set:remoter.input.Header.t_ms)
}

// -------------------------------------------------------------------

// Edge

// .remoter.input.Header hdr = 1;
inline bool Edge::_internal_has_hdr() const {
  return this != internal_default_instance() && _impl_.hdr_ != nullptr;
}
inline bool Edge::has_hdr() const {
  return _internal_has_hdr();
}
inline void Edge::clear_hdr() {
  if (GetArenaForAllocation() == nullptr && _impl_.hdr_ != nullptr) {
    delete _impl_.hdr_;
  }
  _impl_.hdr_ = nullptr;
}
inline const ::remoter::input::Header& Edge::_internal_hdr() const {
  const ::remoter::input::Header* p = _impl_.hdr_;
  return p != nullptr ? *p : reinterpret_cast<const ::remoter::input::Header&>(
      ::remoter::input::_Header_default_instance_);
}
inline const ::remoter::input::Header& Edge::hdr() const {
  // @@protoc_insertion_point(field_get:remoter.input.Edge.hdr)
  return _internal_hdr();
}
inline void Edge::unsafe_arena_set_allocated_hdr(
    ::remoter::input::Header* hdr) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.hdr_);
  }
  _impl_.hdr_ = hdr;
  if (hdr) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:remoter.input.Edge.hdr)
}
inline ::remoter::input::Header* Edge::release_hdr() {
  
  ::remoter::input::Header* temp = _impl_.hdr_;
  _impl_.hdr_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::remoter::input::Header* Edge::unsafe_arena_release_hdr() {
  // @@protoc_insertion_point(field_release:remoter.input.Edge.hdr)
  
  ::remoter::input::Header* temp = _impl_.hdr_;
  _impl_.hdr_ = nullptr;
  return temp;
}
inline ::remoter::input::Header* Edge::_internal_mutable_hdr() {
  
  if (_impl_.hdr_ == nullptr) {
    auto* p = CreateMaybeMessage<::remoter::input::Header>(GetArenaForAllocation());
    _impl_.hdr_ = p;
  }
  return _impl_.hdr_;
}
inline ::remoter::input::Header* Edge::mutable_hdr() {
  ::remoter::input::Header* _msg = _internal_mutable_hdr();
  // @@protoc_insertion_point(field_mutable:remoter.input.Edge.hdr)
  return _msg;
}
inline void Edge::set_allocated_hdr(::remoter::input::Header* hdr) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.hdr_;
  }
  if (hdr) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(hdr);
    if (message_arena != submessage_arena) {
      hdr = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, hdr, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.hdr_ = hdr;
  // @@protoc_insertion_point(field_set_allocated:remoter.input.Edge.hdr)
}

// uint32 hid_usage = 2;
inline void Edge::clear_hid_usage() {
  _impl_.hid_usage_ = 0u;
}
inline uint32_t Edge::_internal_hid_usage() const {
  return _impl_.hid_usage_;
}
inline uint32_t Edge::hid_usage() const {
  // @@protoc_insertion_point(field_get:remoter.input.Edge.hid_usage)
  return _internal_hid_usage();
}
inline void Edge::_internal_set_hid_usage(uint32_t value) {
  
  _impl_.hid_usage_ = value;
}
inline void Edge::set_hid_usage(uint32_t value) {
  _internal_set_hid_usage(value);
  // @@protoc_insertion_point(field_set:remoter.input.Edge.hid_usage)
}

// bool is_down = 3;
inline void Edge::clear_is_down() {
  _impl_.is_down_ = false;
}
inline bool Edge::_internal_is_down() const {
  return _impl_.is_down_;
}
inline bool Edge::is_down() const {
  // @@protoc_insertion_point(field_get:remoter.input.Edge.is_down)
  return _internal_is_down();
}
inline void Edge::_internal_set_is_down(bool value) {
  
  _impl_.is_down_ = value;
}
inline void Edge::set_is_down(bool value) {
  _internal_set_is_down(value);
  // @@protoc_insertion_point(field_set:remoter.input.Edge.is_down)
}

// uint32 modifiers = 4;
inline void Edge::clear_modifiers() {
  _impl_.modifiers_ = 0u;
}
inline uint32_t Edge::_internal_modifiers() const {
  return _impl_.modifiers_;
}
inline uint32_t Edge::modifiers() const {
  // @@protoc_insertion_point(field_get:remoter.input.Edge.modifiers)
  return _internal_modifiers();
}
inline void Edge::_internal_set_modifiers(uint32_t value) {
  
  _impl_.modifiers_ = value;
}
inline void Edge::set_modifiers(uint32_t value) {
  _internal_set_modifiers(value);
  // @@protoc_insertion_point(field_set:remoter.input.Edge.modifiers)
}

// -------------------------------------------------------------------

// Snapshot

// .remoter.input.Header hdr = 1;
inline bool Snapshot::_internal_has_hdr() const {
  return this != internal_default_instance() && _impl_.hdr_ != nullptr;
}
inline bool Snapshot::has_hdr() const {
  return _internal_has_hdr();
}
inline void Snapshot::clear_hdr() {
  if (GetArenaForAllocation() == nullptr && _impl_.hdr_ != nullptr) {
    delete _impl_.hdr_;
  }
  _impl_.hdr_ = nullptr;
}
inline const ::remoter::input::Header& Snapshot::_internal_hdr() const {
  const ::remoter::input::Header* p = _impl_.hdr_;
  return p != nullptr ? *p : reinterpret_cast<const ::remoter::input::Header&>(
      ::remoter::input::_Header_default_instance_);
}
inline const ::remoter::input::Header& Snapshot::hdr() const {
  // @@protoc_insertion_point(field_get:remoter.input.Snapshot.hdr)
  return _internal_hdr();
}
inline void Snapshot::unsafe_arena_set_allocated_hdr(
    ::remoter::input::Header* hdr) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.hdr_);
  }
  _impl_.hdr_ = hdr;
  if (hdr) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:remoter.input.Snapshot.hdr)
}
inline ::remoter::input::Header* Snapshot::release_hdr() {
  
  ::remoter::input::Header* temp = _impl_.hdr_;
  _impl_.hdr_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::remoter::input::Header* Snapshot::unsafe_arena_release_hdr() {
  // @@protoc_insertion_point(field_release:remoter.input.Snapshot.hdr)
  
  ::remoter::input::Header* temp = _impl_.hdr_;
  _impl_.hdr_ = nullptr;
  return temp;
}
inline ::remoter::input::Header* Snapshot::_internal_mutable_hdr() {
  
  if (_impl_.hdr_ == nullptr) {
    auto* p = CreateMaybeMessage<::remoter::input::Header>(GetArenaForAllocation());
    _impl_.hdr_ = p;
  }
  return _impl_.hdr_;
}
inline ::remoter::input::Header* Snapshot::mutable_hdr() {
  ::remoter::input::Header* _msg = _internal_mutable_hdr();
  // @@protoc_insertion_point(field_mutable:remoter.input.Snapshot.hdr)
  return _msg;
}
inline void Snapshot::set_allocated_hdr(::remoter::input::Header* hdr) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.hdr_;
  }
  if (hdr) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(hdr);
    if (message_arena != submessage_arena) {
      hdr = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, hdr, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.hdr_ = hdr;
  // @@protoc_insertion_point(field_set_allocated:remoter.input.Snapshot.hdr)
}

// uint32 modifiers = 2;
inline void Snapshot::clear_modifiers() {
  _impl_.modifiers_ = 0u;
}
inline uint32_t Snapshot::_internal_modifiers() const {
  return _impl_.modifiers_;
}
inline uint32_t Snapshot::modifiers() const {
  // @@protoc_insertion_point(field_get:remoter.input.Snapshot.modifiers)
  return _internal_modifiers();
}
inline void Snapshot::_internal_set_modifiers(uint32_t value) {
  
  _impl_.modifiers_ = value;
}
inline void Snapshot::set_modifiers(uint32_t value) {
  _internal_set_modifiers(value);
  // @@protoc_insertion_point(field_set:remoter.input.Snapshot.modifiers)
}

// bytes pressed_bitmap = 3;
inline void Snapshot::clear_pressed_bitmap() {
  _impl_.pressed_bitmap_.ClearToEmpty();
}
inline const std::string& Snapshot::pressed_bitmap() const {
  // @@protoc_insertion_point(field_get:remoter.input.Snapshot.pressed_bitmap)
  return _internal_pressed_bitmap();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Snapshot::set_pressed_bitmap(ArgT0&& arg0, ArgT... args) {
 
 _impl_.pressed_bitmap_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:remoter.input.Snapshot.pressed_bitmap)
}
inline std::string* Snapshot::mutable_pressed_bitmap() {
  std::string* _s = _internal_mutable_pressed_bitmap();
  // @@protoc_insertion_point(field_mutable:remoter.input.Snapshot.pressed_bitmap)
  return _s;
}
inline const std::string& Snapshot::_internal_pressed_bitmap() const {
  return _impl_.pressed_bitmap_.Get();
}
inline void Snapshot::_internal_set_pressed_bitmap(const std::string& value) {
  
  _impl_.pressed_bitmap_.Set(value, GetArenaForAllocation());
}
inline std::string* Snapshot::_internal_mutable_pressed_bitmap() {
  
  return _impl_.pressed_bitmap_.Mutable(GetArenaForAllocation());
}
inline std::string* Snapshot::release_pressed_bitmap() {
  // @@protoc_insertion_point(field_release:remoter.input.Snapshot.pressed_bitmap)
  return _impl_.pressed_bitmap_.Release();
}
inline void Snapshot::set_allocated_pressed_bitmap(std::string* pressed_bitmap) {
  if (pressed_bitmap != nullptr) {
    
  } else {
    
  }
  _impl_.pressed_bitmap_.SetAllocated(pressed_bitmap, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.pressed_bitmap_.IsDefault()) {
    _impl_.pressed_bitmap_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:remoter.input.Snapshot.pressed_bitmap)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace input
}  // namespace remoter

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_remoter_2eproto
